### ISSUE TITLE
Missing parameter in score_aggregation

### ISSUE THREAD

**Issue by jeromemorignot** [asavinov/intelligent-trading-bot#18]
When running the _signals_ script I'm getting the following error:
`Loading predictions from input file: C:\intelligent-trading-bot-master\DATA_ITB\BTCUSDT\predictions.csv
Predictions loaded. Length: 237774. Width: 27
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\intelligent-trading-bot-master\scripts\signals.py", line 153, in <module>
    main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\intelligent-trading-bot-master\scripts\signals.py", line 91, in main
    aggregate_scores(df, model.get('score_aggregation'), 'buy_score_column', buy_labels)
  File "C:\intelligent-trading-bot-master\common\signal_generation.py", line 34, in aggregate_scores
    raise ValueError(f"Configuration must specify 'score_aggregation' parameters")
ValueError: Configuration must specify 'score_aggregation' parameters
`

I suppose I'm missing a parameter in score_aggregation?

**Comment by asavinov** [comment]
It is a bug while retrieving newly introduced parameters (score_aggregation). I fixed it but the current version is still not thoroughly tested because these changes are preparations to new features to be implemented.
