### ISSUE TITLE
Errors when trying to download binance history

### ISSUE THREAD

**Issue by adiif1** [asavinov/intelligent-trading-bot#28]
Hello!, as in the subject, when I try to download the history, I have these errors, the latest config.
Thanx!

`root@buntu:/home/adiif1/bot/intelligent-trading-bot-master# python3 -m scripts.download_binance -c config-sample-v0.5.0.json 
Start downloading 'BTCUSDT' ...
File not found. All data will be downloaded and stored in newly created file.
Downloading all available 1m data for BTCUSDT. Be patient..!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/adiif1/bot/intelligent-trading-bot-master/scripts/download_binance.py", line 387, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/adiif1/bot/intelligent-trading-bot-master/scripts/download_binance.py", line 104, in main
    klines = App.client.get_historical_klines(
  File "/usr/local/lib/python3.10/dist-packages/binance/client.py", line 984, in get_historical_klines
    return self._historical_klines(
  File "/usr/local/lib/python3.10/dist-packages/binance/client.py", line 1019, in _historical_klines
    start_ts = convert_ts_str(start_str)
  File "/usr/local/lib/python3.10/dist-packages/binance/helpers.py", line 76, in convert_ts_str
    return date_to_milliseconds(ts_str)
  File "/usr/local/lib/python3.10/dist-packages/binance/helpers.py", line 24, in date_to_milliseconds
    d: Optional[datetime] = dateparser.parse(date_str, settings={'TIMEZONE': "UTC"})
  File "/usr/local/lib/python3.10/dist-packages/dateparser/conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dateparser/__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/usr/local/lib/python3.10/dist-packages/dateparser/date.py", line 421, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "/usr/local/lib/python3.10/dist-packages/dateparser/date.py", line 178, in parse
    return instance._parse()
  File "/usr/local/lib/python3.10/dist-packages/dateparser/date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "/usr/local/lib/python3.10/dist-packages/dateparser/date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/usr/local/lib/python3.10/dist-packages/dateparser/date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
  File "/usr/local/lib/python3.10/dist-packages/dateparser/languages/locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
  File "/usr/local/lib/python3.10/dist-packages/dateparser/languages/locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
  File "/usr/local/lib/python3.10/dist-packages/dateparser/languages/locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
  File "/usr/local/lib/python3.10/dist-packages/regex/regex.py", line 710, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "/usr/local/lib/python3.10/dist-packages/regex/_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
root@buntu:/home/adiif1/bot/intelligent-trading-bot-master# `

**Comment by iploshchik** [comment]
Delete collector.log file in your main folder; re-run the script, keep an eye on any errors, appearing in collector.log file and post them here.
