### ISSUE TITLE
KeyError: features_kline

### ISSUE THREAD

**Issue by itsXactlY** [asavinov/intelligent-trading-bot#37]
Hey, still in the process of figuring out and feel a bit lost, when i run; "python -m scripts.grid_search" it errors like;

>  2023-10-13 20:47:06 ⌚  alca in ~/projects/intelligent-trading-bot
> ± |master ?:5 ✗| → python -m scripts.grid_search
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/home/alca/projects/intelligent-trading-bot/scripts/grid_search.py", line 24, in <module>
>     features_kline = App.config["features_kline"]
>                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
> KeyError: 'features_kline'

**Comment by asavinov** [comment]
the functions of ``grid_search`` are in ``train_signals`` so I removed it.
