### ISSUE TITLE
Hi, I encountered an issue while executing the following command after your recent commit: python -m scripts.train_signals -c .\configs\config.jsonc.

### ISSUE THREAD

**Issue by iaananth** [asavinov/intelligent-trading-bot#42]
python -m scripts.train_signals -c .\configs\config.jsonc
2023-12-12 22:28:15.543659: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\RLDC\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Loading signals from input file: C:\DATA_ITB\BTCUSDT\signals.csv
Signals loaded. Length: 525600. Width: 10
Input data size 525600 records. Range: [2022-12-12 10:54:00, 2023-12-12 10:53:00]
MODELS:   0%|                                                                                                      | 0/36 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\dell laptop E backup\mainbackup\trd\2025\check\intelligent-trading-bot\scripts\train_signals.py", line 258, in <module>
    main()
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\RLC\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\dell laptop E backup\mainbackup\trd\2025\check\intelligent-trading-bot\scripts\train_signals.py", line 178, in main
    apply_rule_with_score_thresholds(df, score_column_names, trade_model)
  File "D:\dell laptop E backup\check\intelligent-trading-bot\common\gen_signals.py", line 209, in apply_rule_with_score_thresholds
    signal_column = model.get("signal_columns")[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by asavinov** [comment]
Thanks! Indeed, it is a consequence of last changes in the config structure. I will fix this...

**Comment by iaananth** [comment]
@asavinov Thank you. I accidentally opened one more issue. If possible, please close or delete it.

**Comment by iaananth** [comment]
@asavinov 
i got this err.
is that normal need err handling ?

2023-12-24 22:32:00,012 INFO ===> Start collector task. Timestamp 1703437320012. Interval [1703437320000,1703437380000].
2023-12-24 22:32:00,142 DEBUG https://api.binance.com:443 "GET /api/v3/klines?endTime=1703437320012&interval=1m&limit=3&symbol=BTCUSDT HTTP/1.1" 200 209
2023-12-24 22:32:00,143 DEBUG Stored klines. Total 100 in db. Last kline end: 1703437320000. Current time: 1703437320143
2023-12-24 22:32:00,143 INFO <=== End collector task.
2023-12-24 22:32:00,144 INFO Analyze BTCUSDT. Last kline timestamp: 2023-12-24 17:01:00
2023-12-24 22:32:00,187 INFO Analyze finished. Close: 43,670 Signals: trade_score,buy_signal_column,sell_signal_column
2023-12-24 22:32:00,188 INFO ===> Start trade task. Timestamp 1703437320188. Interval [1703437320000,1703437380000].
2023-12-24 22:32:00,188 ERROR Wrong status value None.
2023-12-24 22:32:00,188 ERROR Task exception was never retrieved
future: <Task finished name='Task-42' coro=<main_trader_task() done, defined at D:\dell\bot\intelligent-trading-bot\service\trader.py:31> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "D:\dell\bot\intelligent-trading-bot\service\trader.py", line 99, in main_trader_task
    signal_side = signal.get("side")
AttributeError: 'NoneType' object has no attribute 'get'
